name: rx_observable
description: "Simple reactive variables and widgets"
version: 0.5.4
homepage: https://github.com/aleexam/rx_observable
issue_tracker: https://github.com/aleexam/rx_observable/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:



