name: rx_observable
description: "Simple reactive variables and widgets. Ideal to use with MVVM like patterns."
version: 0.7.1
homepage: https://github.com/aleexam/rx_observable
issue_tracker: https://github.com/aleexam/rx_observable/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
